FROM oracle/database:19.3.0-se2
COPY *.sql /docker-entrypoint-initdb.d/
#ENV ORACLE_SID 'cdb' 
#ENV ORACLE_PDB 'osadb'
#ENV ORACLE_PWD 'qwe123'
#ENV DB_SID 'cdb' 
#ENV DB_PDB 'osadb'
#ENV DB_PASSWD 'gvinbleid'
#ENV DB_DOMAIN 'ru.oracle.com'
