version: '3'

services:
  db_postgres:
    build:
        context: ./conf.d/postgres
    ports:
      - 5432:5432
    image: db_postgres
    container_name: db_postgres

  db_mysql:
    build:
        context: ./conf.d/mysql
    ports:
      - 3306:3306
    image: db_mysql
    container_name: db_mysql
    command: --default-authentication-plugin=mysql_native_password

  db_oracle:
    build:
        context: ./conf.d/oracle
    ports:
      - 1521:1521
      - 5500:5500
    image: db_oracle
    container_name: db_oracle

  db_mongo:
    build:
        context: ./conf.d/mongo
    ports:
      - 27017:27017
    image: db_mongo
    container_name: db_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwe123

  mongo-express:
    image: mongo-express
    ports:
      - 2988:8081
    depends_on:
      - db_mongo
    container_name: mongo-express
    links:
      - db_mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwe123
      ME_CONFIG_MONGODB_SERVER: db_mongo
      ME_CONFIG_BASICAUTH_USERNAME: andrey
      ME_CONFIG_BASICAUTH_PASSWORD: qwe123

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 2987:8080
