version: '3.1'

services:

  db:
    image: postgres
    #restart: always
    container_name: postgres_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: andrey
      POSTGRES_PASSWORD: qwe123
      POSTGRES_DB: report_cards


  adminer:
    image: adminer
    #restart: always
    container_name: adminer
    ports:
      - 2987:8080
