CREATE OR REPLACE NONEDITIONABLE PACKAGE FILL_EDUCATION AS

    PROCEDURE GET_POSTGRES_DATA;
    PROCEDURE GET_MYSQL_DATA;
    PROCEDURE GET_ORALCE_DATA;
    PROCEDURE GET_MONGODB_DATA;

END FILL_EDUCATION;
